version: "2"

services:
  proxy:
    image: jwilder/nginx-proxy:alpine
    ports:
      - "80:80"
    volumes:
      - "/var/run/docker.sock:/tmp/docker.sock"

  #database
  db:
    image: postgres
    ports:
      - "3305:5432"
    volumes:
      - "./database:/var/lib/postgresql/data"
    env_file:
      - "./env_files/db.env"

  db-adminer:
    image: adminer
    ports:
      - 8081:8080
    environment:
      VIRTUAL_HOST: "adminer.dorms.localhost"

  #python app
  api:
    build: .
    ports:
      - "5000:5000"
    env_file:
      - "./env_files/db.env"
      - "./env_files/api.env"
    volumes:
      - "./:/dorm-be/"
    links:
      - db
    stdin_open: true
    tty: true
    dns: "8.8.8.8"
